[build]
builder = "DOCKERFILE"
dockerfilePath = "core/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/game-version"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
